@host = localhost
@port = 5111


### relCompuestosGrupo/ 
#* allowedFields = ["id", "grupoId", "grupo", "compuestoId", "compuesto", "matrizCompuestoId", "matrizCompuesto", "matrizGrupoId", "MatrizGrupo"];

### GET 
### ? Todos los analisis
GET http://{{host}}:{{port}}/api/analisisrequeridos/

### ? Analisis por grupo
# Este request filtra los analisis con metodo que contiene "8015"
# Formato interno: ["metodo","contains","8015"]
GET http://{{host}}:{{port}}/api/analisisrequeridos?$filter=[%22metodo%22%2C%22contains%22%2C%228015%22]


### ? Get por ID
GET http://{{host}}:{{port}}/api/analisisRequeridos/2

### Updates
### ? Actualizar un analisis
PUT http://{{host}}:{{port}}/api/analisisrequeridos/2
Content-Type: application/json

{
  "compuestoId": 8
}


### Create
### ? Crear un Analisis Requerido 
POST http:/{{host}}:{{port}}/api/analisisrequeridos/
Content-Type: application/json

{
  "cadenaCustodiaId": 1,
  "tipo": 2,
  "grupoId": null,
  "compuestoId": 8,
  "metodoId": 6
}

### Delete
### ? Borrar un analisis que no existe
DELETE http://{{host}}:{{port}}/api/analisisrequeridos/35

### Delete
### ? Borrar un analisis que sí existe
DELETE http://{{host}}:{{port}}/api/relCompuestoGrupo/4
