@host = localhost
@port = 5111
### LQS/ 
#* allowedFields = ["id", "laboratorioId", "compuestoId", "valorLQ"];

### GET 
### ? Todas los LQs
GET http://{{host}}:{{port}}/api/lqs/

### ? LQs por el laboratorioId
# Este request filtra compuesto con laboratorioId = '1'
# Formato interno: ["laboratorioId","=","1"]
GET http://{{host}}:{{port}}/api/lqs?$filter=[%22laboratorioId%22%2C%22%3D%22%2C%221%22]


### ? Get por ID
GET http://{{host}}:{{port}}/api/lqs/2

### Updates
### ? Actualizar un LQ que no existe
PUT http://{{host}}:{{port}}/api/lqs/45
Content-Type: application/json

{
  "laboratorioId": 2,
  "compuestoId": 5,
  "metodoId": 1,
  "UMId": 2,
  "valorLQ": 3,
  "matrizId": 2
}

### ? Actualizar un LQ
PUT http://{{host}}:{{port}}/api/lqs/2
Content-Type: application/json

{
  "laboratorioId": 1,
  "compuestoId": 10,
  "metodoId": 1,
  "UMId": 2,
  "valorLQ": 3,
  "matrizId": 2
}


### Create
### ? Crear un LQ 
POST http://{{host}}:{{port}}/api/lqs/
Content-Type: application/json

{
  "laboratorioId": 3,
  "compuestoId": 4,
  "metodoId": 2,
  "UMId": 2,
  "valorLQ": 4.1,
  "matrizId": 1
}

### Create
### ? Crear un LQ 
POST http://{{host}}:{{port}}/api/lqs/
Content-Type: application/json

{
  "laboratorioId": 4,
  "compuestoId": 5,
  "metodoId": 1,
  "UMId": 2,
  "valorLQ": 2.1,
  "matrizId": 2
}

### Delete
### ? Borrar un LQS que no existe
DELETE http://{{host}}:{{port}}/api/lqs/5

### Delete
### ? Borrar una autoridad de aplicacion sí existe
DELETE http://{{host}}:{{port}}/api/lqs/10
