@host = localhost
@port = 5111
### laboratorios/ 
#* allowedFields = ["id", "nombre", "domicilio", "formato"];

### GET 
### ? Todos los laboratorios
GET http://{{host}}:{{port}}/api/laboratorios/

### ? Get por ID
GET http://{{host}}:{{port}}/api/laboratorios/1

### ? Laboratorio por el nombre
# Este request filtra laboratorio cuya nombre = 'LABCA'
# Formato interno: ["nombre","=","LABCA"]
GET http://{{host}}:{{port}}/api/laboratorios?$filter=[%22nombre%22%2C%22%3D%22%2C%22LABCA%22]

### Updates
### ? Actualizar un laboratorio que no existe
PUT http://{{host}}:{{port}}/api/laboratorios/9
Content-Type: application/json

{
  "nombre": "LABCA SA",
  "domicilio": "Y526 N 1510 1/2, Tolosa, Bs As",
  "formato": "1"
}

### ? Actualizar un laboratorio
PUT http://{{host}}:{{port}}/api/laboratorios/2
Content-Type: application/json

{
  "nombre": "LABCA SA",
  "domicilio": "526 N 1510 1/2, Tolosa, Bs As",
  "formato": "1"
}


### Create
### ? Crear un Laboratorio 
POST http://{{host}}:{{port}}/api/laboratorios/
Content-Type: application/json

{
  "nombre": "Analisis SA",
  "domicilio": "Potosi 3870, CABA",
  "formato": "3"
}


### Delete
### ? Borrar un labortorio que no existe
DELETE http://{{host}}:{{port}}/api/laboratorios/15

### Delete
### ? Borrar un labortorio que sí existe
DELETE http://{{host}}:{{port}}/api/laboratorios/3




###
http://{{host}}:{{port}}/api/proyectos?%24filter=%5B%22codigo%22%2C%22contains%22%2C%22200222%22%5D&%24sort=%5B%7B%22selector%22%3A%22nombre%22%2C%22desc%22%3Atrue%7D%2C%7B%22selector%22%3A%22id%22%2C%22desc%22%3Afalse%7D%5D&%24skip=0&%24take=10
