### GraficosGrupos/ 
#* allowedFields = ["id", "subproyectoId", "nombre", "pozos", "graficos"];

### GET 
### ? Todos los GraficosGrupos
GET http://localhost:5001/graficosGrupos/

### ? GraficosGrupos por nombre
# Este request filtra graficosGrupos con nombre = 'Gr1'
# Formato interno: ["nombre","=","Gr1"]
GET http://localhost:5001/graficosGrupos?$filter=[%22nombre%22%2C%22%3D%22%2C%22Gr1%22]


### ? Get por ID
GET http://localhost:5001/graficosGrupos/1

### Updates
### ? Actualizar un graficoGrupo que no existe
PUT http://localhost:5001/graficosGrupos/45
Content-Type: application/json

{
  "subproyectoId": 999,
  "nombre": "Gr2-modificado",
  "pozos": [33],
  "graficos": [1]
}

### ? Actualizar un graficoGrupo
PUT http://localhost:5001/graficosGrupos/2
Content-Type: application/json

{
  "subproyectoId": 999,
  "nombre": "Gr2-modificado",
  "pozos": [33],
  "graficos": [1]
}


### Create
### ? Crear un Grafico 
POST http://localhost:5001/graficosGrupos/
Content-Type: application/json

{
  "subproyectoId": 999,
  "nombre": "Gr3-nuevo",
  "pozos": [34],
  "graficos": [1]
}

### Delete
### ? Borrar un graficoGrupo que no existe
DELETE http://localhost:5001/graficosGrupos/35

### Delete
### ? Borrar un labortorio que sí existe
DELETE http://localhost:5001/graficosGrupos/3
