@host = localhost
@port = 5111

### matrizcadena/ 

### GET 
### ? matriz de un evento
GET http://{{host}}:{{port}}/api/matrizcadena?eventoId=222

### ? matriz de una cadenas de custodia
GET http://{{host}}:{{port}}/api/matrizcadena?cadenaId=150

