@host = localhost
@port = 5111
### PROVINCIAS/ 

### GET 
### ? Todas las Provincias
GET http://{{host}}:{{port}}/api/provincias/


### ? Get por ID
GET http://{{host}}:{{port}}/api/provincias/3

### POZOSTIPO/ 

### GET 
### ? Todas las Provincias
GET http://{{host}}:{{port}}/api/pozosTipo/


### ? Get por ID
GET http://{{host}}:{{port}}/api/pozosTipo/1

### POZOSESTADO/ 

### GET 
### ? Todas las Provincias
GET http://{{host}}:{{port}}/api/pozosEstado/


### ? Get por ID
GET http://{{host}}:{{port}}/api/pozosEstado/2