@host = localhost
@port = 5111### MATRIZ/ 

### GET 
### ? Todas las Matrices
GET http://{{host}}:{{port}}/api/compuestos/
/matriz/


### ? Get por ID
GET http://{{host}}:{{port}}/api/compuestos/
/matriz/3