POST http://localhost:5001/protocolos
Content-Type: application/json

{
  "formData": {
    "evento": 4,
    "laboratorio": 2,
    "adelanto": [{ "name": "Protocolo_125.xlsx" }],
    "matrizId": 1
  },
  "adelantoData": {
    "data": [
      { 
        "compuestoLab": "BTEX", 
        "compuestoId": 39, 
        "metodoLab": "EPA 8260", 
        "metodoId": 5, 
        "unidadLab": "µg/L", 
        "unidadId": 2, 
        "Muestra MA F7/3": "5.4" 
      }
    ],
    "muestras": [
      { 
        "muestraLab": "Muestra MA F7/3", 
        "muestraCadena": 7 
      }
    ]
  }
}

### GET con el formato de las tablas
GET http://localhost:5001/protocolos/12/extended

### GET con el formato de frontend
GET http://localhost:5001/protocolos/12/original

### Get ALL basico
GET http://localhost:5001/protocolos/