@host = localhost
@port = 5111

### sinonimoscompuestos/  sinonimosmetodos
#* allowedFields = ["id", "laboratorioId", "textoLab", "textoProcesado", "componenteId", "componente"];

### GET 
### ? Todos los sinonimos de compuestos
GET http://{{host}}:{{port}}/api/sinonimoscompuestos/

### ? Todos los sinonimos de metodos
GET http://{{host}}:{{port}}/api/sinonimosmetodos/

### ? Todos los sinonimos de ums
GET http://{{host}}:{{port}}/api/sinonimosums/


### GET BY ID
### ? Get sinonimo compuestos por ID
GET http://{{host}}:{{port}}/api/sinonimoscompuestos/2

### ? Get sinonimo metodos por ID
GET http://{{host}}:{{port}}/api/sinonimosmetodos/2

### ? Get sinonimo um por ID
GET http://{{host}}:{{port}}/api/sinonimosums/2


### Converir x sinonimos
### ? Sinonimos de compuestos
POST http://{{host}}:{{port}}/api/sinonimoscompuestos/listasinonimos
Content-Type: application/json

{
  "matrizId": 1,
  "compuestosOriginales": ["MRO C28-C35*", "1,2,4-Trimetilbenceno","*No me/vas- a Encontrar", "Con ácentís /*y màs"]
}

### ? Sinonimos de metodos
POST http://{{host}}:{{port}}/api/sinonimosmetodos/listasinonimos
Content-Type: application/json

{
  "metodosOriginales": ["EPA 3051 A/ 6010 D", "*Otro metodo"]
}

### ? Sinonimos de um
POST http://{{host}}:{{port}}/api/sinonimosums/listasinonimos
Content-Type: application/json

{
  "umsOriginales": ["ug/l", "mg/l", "otro"]
}

### Updates
### ? Actualizar un sinonimo compuesto
PUT http://{{host}}:{{port}}/api/sinonimoscompuestos/2
Content-Type: application/json

{
  "compuestoId": 8
}

### ? Actualizar un sinonimo metodo
PUT http://{{host}}:{{port}}/api/sinonimosmetodos/2
Content-Type: application/json

{
  "metodoId": 8
}

### ? Actualizar un sinonimo um
PUT http://{{host}}:{{port}}/api/sinonimosums/2
Content-Type: application/json

{
  "umId": 2
}


### Create
### ? Crear un Sinonimo compuesto 
POST http://{{host}}:{{port}}/api/sinonimoscompuestos/
Content-Type: application/json

{
  "textoLab": "MRO C28-C35*",
  "textoProcesado": "mroc28c351",
  "compuestoId": 22,
  "matrizId": 1
}


### ? Crear un Sinonimo metodo 
POST http://{{host}}:{{port}}/api/sinonimosmetodos/
Content-Type: application/json

{
  "textoLab": "EPA 3510 C Rev 03 (1996) / EPA 8270 E Rev 06 (2018)",
  "textoProcesado": "epa3510crev03(1996)epa8270erev06(2018)",
  "metodoId": 6
}


### ? Crear un Sinonimo um 
POST http://{{host}}:{{port}}/api/sinonimosums/
Content-Type: application/json

{
  "textoLab": "g/lm",
  "textoProcesado": "glm",
  "umId": 11
}


### Delete
### ? Borrar un analisis que no existe
DELETE http://{{host}}:{{port}}/api/sinonimoscompuestos/35

### Delete
### ? Borrar un analisis que sí existe
DELETE http://{{host}}:{{port}}/api/sinonimoscompuestos/4
