### autaplicacion/ 
#* allowedFields = ["id", "nombre"];

### GET 
### ? Todas los Clientes
GET http://localhost:5001/clientes/

### ? Clientes por el nombre
# Este request filtra cliente con nombre = 'YPF'
# Formato interno: ["nombre","=","YPF"]
GET http://localhost:5001/clientes?$filter=[%22nombre%22%2C%22%3D%22%2C%22YPF%22]


### ? Get por ID
GET http://localhost:5001/clientes/3

### Updates
### ? Actualizar un cliene
PUT http://localhost:5001/clientes/2
Content-Type: application/json

{
  "nombre": "Vista Energy Argentina"
}


### Create
### ? Crear un cliente 
POST http://localhost:5001/clientes/
Content-Type: application/json

{
  "codigo": "100500",
  "nombre": "PlusPetrol"
}


### Delete
### ? Borrar un cliente que no existe
DELETE http://localhost:5001/clientes/77

### Delete
### ? Borrar un cliente que sí existe
DELETE http://localhost:5001/clientes/3
