@host = localhost
@port = 5111
### compuestos/ 
#* allowedFields = ["id", "nombre", "sinonimo", "funcion", "agrupacion"];

### GET 
### ? Todos los compuestos
GET http://{{host}}:{{port}}/api/compuestos/

### ? Compuestos por el sinonimo
# Este request filtra compuesto con sinonimo = 'gro'
# Formato interno: ["sinonimo","=","gro"]
GET http://{{host}}:{{port}}/api/compuestos?$filter=[%22nombre%22%2C%22%3D%22%2C%22Xilenos%22]


### ? Get por ID
GET http://{{host}}:{{port}}/api/compuestos/3

### Updates
### ? Actualizar un compuestp que no existe
PUT http://{{host}}:{{port}}/api/compuestos/45
Content-Type: application/json

{
  "nombre": "Hidrocarburos Totales (GRO + DRO)",
  "sinonimo": "hidrocarburostotales",
  "funcion": 1,
  "agrupaEn": 1,
  "exponeId": 1,
  "matrizCodigo": 2
}

### ? Actualizar un Compuesto
PUT http://{{host}}:{{port}}/api/compuestos/2
Content-Type: application/json

{
  "nombre": "DRO (Diesel Range Organics)",
  "sinonimo": "dro",
  "funcion": 2,
  "agrupaEn": 1,
  "exponeId": 1,
  "matrizCodigo": 2
}


### Create
### ? Crear un Compuesto 
POST http://{{host}}:{{port}}/api/compuestos/
Content-Type: application/json

{
  "nombre": "Metil ter-Butil Eter (MTBE)*",
  "sinonimo": "mtbe",
  "funcion": 2,
  "agrupaEn": 0
}

### Delete
### ? Borrar un compuesto que no existe
DELETE http://{{host}}:{{port}}/api/compuestos/35

### Delete
### ? Borrar un labortorio que sí existe
DELETE http://{{host}}:{{port}}/api/compuestos/4
