### relCompuestosGrupo/ 
#* allowedFields = ["id", "grupoId", "grupo", "compuestoId", "compuesto", "matrizCompuestoId", "matrizCompuesto", "matrizGrupoId", "MatrizGrupo"];

### GET 
### ? Todos los analisis
GET http://localhost:5001/analisisrequeridos/

### ? Analisis por grupo
# Este request filtra los analisis con metodo que contiene "8015"
# Formato interno: ["metodo","contains","8015"]
GET http://localhost:5001/analisisrequeridos?$filter=[%22metodo%22%2C%22contains%22%2C%228015%22]


### ? Get por ID
GET http://localhost:5001/analisisRequeridos/2

### Updates
### ? Actualizar un analisis
PUT http://localhost:5001/analisisrequeridos/2
Content-Type: application/json

{
  "compuestoId": 8
}


### Create
### ? Crear un Analisis Requerido 
POST http://localhost:5001/analisisrequeridos/
Content-Type: application/json

{
  "cadenaCustodiaId": 1,
  "tipo": 2,
  "grupoId": null,
  "compuestoId": 8,
  "metodoId": 6
}

### Delete
### ? Borrar un analisis que no existe
DELETE http://localhost:5001/analisisrequeridos/35

### Delete
### ? Borrar un analisis que sí existe
DELETE http://localhost:5001/relCompuestoGrupo/4
