### Obtener todos los datos de cadenas para un subproyecto/matriz/Compuesto
### Obtener datos para subproyecto 29, matriz 1, compuesto 25
GET http://localhost:5001/cadenasSubproyectoCompuesto/266/1/1


### Obtener valores en tabla plana
GET http://localhost:5001/cadenasSubproyectoCompuesto/valoresSubproyecto/55
