@host = localhost
@port = 5111
### pozos/ 
#* allowedFields = ["id", "subproyectoId", "nombre", "estado", "tipo"];

### GET 
### ? Todos los pozos
GET http://{{host}}:{{port}}/api/pozos/

### ? Filtra Pozos que se llamen PM4 
# Este request filtra los pozos con nombre  = 'PM4'
# Formato interno: ["nombre","=","PM4"]
GET http://{{host}}:{{port}}/api/pozos?$filter=[%22nombre%22%2C%22%3D%22%2C%22PM4%22]

### GET by Id
### ? 
GET http://{{host}}:{{port}}/api/pozos/1

### Updates
### ? Actualizar un pozo que no existe
PUT http://{{host}}:{{port}}/api/pozos/999
Content-Type: application/json

{
  "subproyectoId": 151,
  "nombre": "PM15",
  "estado": 1,
  "tipoId": 1,
  "latitud": null,
  "longitud": null,
  "UltMuestraAguaIdx": 1,
  "UltMuestraFLNAIdx": 0,
  "UltMuestraGasIdx": 1
  
}

### ? Actualizar un pozo
PUT http://{{host}}:{{port}}/api/pozos/1
Content-Type: application/json

{
  "id": 1,
  "subproyectoId": 151,
  "nombre": "PM11",
  "estadoId": 1,
  "tipoId": 3,
  "latitud": null,
  "longitud": null,
  "UltMuestraAguaIdx": 1,
  "UltMuestraFLNAIdx": 0,
  "UltMuestraGasIdx": 2
  
}

### Create
### ? Crear un pozo con campos invalidos
POST http://{{host}}:{{port}}/api/pozos/
Content-Type: application/json

{
  "subproyectoId": 5,
  "subproyecto": "300119-03",
  "nombre": "99",
  "estadoId": 99,
  "tipoId": 99,
  "UltMuestraAguaIdx": 5,
  "UltMuestraFLNAIdx": 0,
  "UltMuestraGasIdx": 2
  
}


### Create
### ? Crear un pozo 
POST http://{{host}}:{{port}}/api/pozos/
Content-Type: application/json

{
  "subproyectoId": 151,
  "nombre": "99",
  "estadoId": 1,
  "tipoId": 1,
  "UltMuestraAguaIdx": 5,
  "UltMuestraFLNAIdx": 0,
  "UltMuestraGasIdx": 2
}

### Delete
### ? Borrar un pozo
DELETE http://{{host}}:{{port}}/api/pozos/1009

###
http://{{host}}:{{port}}/api/proyectos?%24filter=%5B%22codigo%22%2C%22contains%22%2C%22200222%22%5D&%24sort=%5B%7B%22selector%22%3A%22nombre%22%2C%22desc%22%3Atrue%7D%2C%7B%22selector%22%3A%22id%22%2C%22desc%22%3Afalse%7D%5D&%24skip=0&%24take=10
