@host = localhost
@port = 5111
### subproyectos
#* allowedFields = ["id", "codigo", "nombreLocacion", "ubicacion", "autAplicacionId", "proyectoId"];
#* getFields = allowedFields + "proyecto" + "autoridad"

### GET 
### ? Todos los proyectos
GET http://{{host}}:{{port}}/api/subproyectos/

### ? Todos los subproyectos cn filtro simple
# Este request filtra subproyectos que comienzan con 
# Formato interno: ["codigo","startswith","300115"]
GET http://{{host}}:{{port}}/api/subproyectos?$filter=%5B%22codigo%22%2C%22startswith%22%2C%22300115%22%5D

### GET by Id
### ? 
GET http://{{host}}:{{port}}/api/subproyectos/1


### Create
POST http://{{host}}:{{port}}/api/subproyectos/
Content-Type: application/json

{
  "proyectoId": 24,
  "codigo": "300115",
  "nombreLocacion": "Locación Norte",
  "ubicacion": "Argentina - Neuquén - LLL",
  "apies": "COD-YPF",
  "objetivo": "Vactor + GeoRadar",
  "notas": "exProyecto 197115",
  "autAplicacionAguaId": 3,
  "autAplicacionSueloId": 4,
  "autAplicacionGasesId": 4,
  "autAplicacionFLNAId": 3
}

### DELETE
### ? 
DELETE  http://{{host}}:{{port}}/api/subproyectos/5
