@host = localhost
@port = 5111
### proyectosEstado/ 

### GET 
### ? Todos los estados
GET http://{{host}}:{{port}}/api/proyectosestado/


### ? Get por ID
GET http://{{host}}:{{port}}/api/proyectosestado/2