### pozos/ 
#* allowedFields = ["id", "pozoId", "eventoMuestreoId", "nombre", "tipo", "cantViales", "cantBotellas05", "cantBotellas1", "cantBotellas2"];

### GET 
### ? Todos las muestras
GET http://localhost:5001/muestras/

### ? Filtra muestra que se llamen "Muestra 1-1" 
# Este request filtra la muestra con nombre = 'Muestra 1-1'
# Formato interno: ["nombre","=","Muestra 1-1"]
GET http://localhost:5001/muestras?$filter=[%22nombre%22%2C%22%3D%22%2C%22Muestra 1-N%22]

### GET by Id
### ? 
GET http://localhost:5001/muestras/1

### Updates
### ? Actualizar una muestra 
PUT http://localhost:5001/muestras/9
Content-Type: application/json

{
  "pozoId": 1,
  "cadenaCustodiaId": 1,
  "nombre": "Muestra 1-1",
  "tipo": 1,
  "nivelFreatico": 1.32,
  "profundidad": 0,
  "flna": 0,
  "cadenaOPDS": "",
  "protocoloOPDS": ""    
}



### Create
### ? Crear una muestra 
POST http://localhost:5001/muestras/
Content-Type: application/json

{
  "pozoId": 3,
  "cadenaCustodiaId": 1,
  "nombre": "Muestra 1-1",
  "tipo": 1,
  "nivelFreatico": 1.32,
  "profundidad": 0,
  "flna": 0,
  "cadenaOPDS": "",
  "protocoloOPDS": ""      
}

### Delete
### ? Borrar una muestra
DELETE http://localhost:5001/muestras/3

