@host = localhost
@port = 5111
### metodos/ 
#* allowedFields = ["id", "nombre", " sinonimo", " funcion" ];

### GET 
### ? Todas los Metodos
GET http://{{host}}:{{port}}/api/metodos/

### ? Metodos por el nombre
# Este request filtra cliente con nombre = 'EPA 418'
# Formato interno: ["nombre","=","EPA 418"]
GET http://{{host}}:{{port}}/api/metodos?$filter=[%22nombre%22%2C%22%3D%22%2C%22EPA 418%22]


### ? Get por ID
GET http://{{host}}:{{port}}/api/metodos/3

### Updates
### ? Actualizar un metodo
PUT http://{{host}}:{{port}}/api/metodos/3
Content-Type: application/json

{
  "sinonimo": "tnrcc 1005",
  "funcion": 4
}


### Create
### ? Crear un cliente 
POST http://{{host}}:{{port}}/api/metodos/
Content-Type: application/json

{
  "nombre": "EPA nosecuanto",
  "sinonimo": "nosecuanto",
  "funcion": 2
}

### Delete
### ? Borrar un metodo
DELETE http://{{host}}:{{port}}/api/metodos/7
