### autaplicacion/ 
#* allowedFields = ["id", "nombre", "sitioWeb1", "sitioWeb2"];

### GET 
### ? Todas lss autoridades de aplicacion
GET http://localhost:5001/autaplicacion/

### ? Autoridades de aplicación por el nombre
# Este request filtra compuesto con nombre = 'Nacion'
# Formato interno: ["nombre","=","Nacion"]
GET http://localhost:5001/autaplicacion?$filter=[%22nombre%22%2C%22%3D%22%2C%22Nacion%22]


### ? Get por ID
GET http://localhost:5001/autaplicacion/3

### Updates
### ? Actualizar una autoridad de aplicacion que no existe
PUT http://localhost:5001/autaplicacion/45
Content-Type: application/json

{
  "nombre": "Nacion",
  "sitioWeb1": "www.nacion.com",
  "sitioWeb2": ""
}

### ? Actualizar una autoridad de aplicación
PUT http://localhost:5001/autaplicacion/2
Content-Type: application/json

{
  "nombre": "La Matanza  II",
  "sitioWeb1": "www.LaMatanza.gob.ar",
  "sitioWeb2": "www.LaMatanza.gob.ar II"
}


### Create
### ? Crear una Autoridad de aplicacion 
POST http://localhost:5001/autaplicacion/
Content-Type: application/json

{
  "nombre": "La Matanza",
  "sitioWeb1": "www.LaMatanza.gob.ar",
  "sitioWeb2": ""
}

### Create
### ? Crear una Autoridad de aplicacion 
POST http://localhost:5001/autaplicacion/
Content-Type: application/json

{
  "nombre": "Provincia de Neuquen",
  "sitioWeb1": "www.Neuquen.gob.ar",
  "sitioWeb2": "www.Neuquen.gob.ar II"
}


### Delete
### ? Borrar un compuesto que no existe
DELETE http://localhost:5001/autaplicacion/35

### Delete
### ? Borrar una autoridad de aplicacion sí existe
DELETE http://localhost:5001/autaplicacion/2
