@host = localhost
@port = 5111
### autaplicacion/ 
#* allowedFields = ["id", "nombre"];

### GET 
### ? Todas los Clientes
GET http://{{host}}:{{port}}/api/clientes/

### ? Clientes por el nombre
# Este request filtra cliente con nombre = 'YPF'
# Formato interno: ["nombre","=","YPF"]
GET http://{{host}}:{{port}}/api/clientes?$filter=[%22nombre%22%2C%22%3D%22%2C%22YPF%22]


### ? Get por ID
GET http://{{host}}:{{port}}/api/clientes/3

### Updates
### ? Actualizar un cliene
PUT http://{{host}}:{{port}}/api/clientes/2
Content-Type: application/json

{
  "nombre": "Vista Energy Argentina"
}


### Create
### ? Crear un cliente 
POST http://{{host}}:{{port}}/api/clientes/
Content-Type: application/json

{
  "codigo": "100500",
  "nombre": "PlusPetrol"
}


### Delete
### ? Borrar un cliente que no existe
DELETE http://{{host}}:{{port}}/api/clientes/77

### Delete
### ? Borrar un cliente que sí existe
DELETE http://{{host}}:{{port}}/api/clientes/3
