@host = localhost
@port = 5111

### Obtener todos los datos de cadenas para un subproyecto/matriz/Compuesto
### Obtener datos para subproyecto 151, matriz 1, compuesto 25
GET http://{{host}}:{{port}}/api/cadenasSubproyectoCompuesto/151/1/1


### Obtener valores en tabla plana
GET http:/{{host}}:{{port}}/api/cadenasSubproyectoCompuesto/valoresSubproyecto/266
