@host = localhost
@port = 5111
### autaplicacion/ 
#* allowedFields = ["id", "nombre"];

### GET 
### ? Todas las unidades de medida
GET http://{{host}}:{{port}}/api/um/

### ? Unidades de medida con nombre que contiene mg
# Formato interno: ["nombre","contains","mg"]
GET http://{{host}}:{{port}}/api/um?$filter=[%22nombre%22%2C%22%contains%22%2C%22mg%22]


### ? Get por ID
GET http://{{host}}:{{port}}/api/um/2

### Updates
### ? Actualizar una um
PUT http://{{host}}:{{port}}/api/um/3
Content-Type: application/json

{
  "nombre": "mg/L"
}


### Create
### ? Crear un cliente 
POST http://{{host}}:{{port}}/api/um/
Content-Type: application/json

{
  "nombre": "cm3"
}


### Delete
### ? Borrar un cliente que no existe
DELETE http://{{host}}:{{port}}/api/clientes/77

### Delete
### ? Borrar un cliente que sí existe
DELETE http://{{host}}:{{port}}/api/clientes/3
