@host = localhost
@port = 5111

### eventomuestreo/ 
#* allowedFields = ["id", "fecha", "subproyectoId", "nombre", "cadenaCustodiaLink"];

### GET 
### ? Todos los eventos de nuestreo
GET http://{{host}}:{{port}}/api/cadenascustodia/

### ? Filtra Cadenas de Custodia  
# Este request filtra los Eventos de Muestreo del eventoMuestreoId  = 1
# Formato interno: ["eventoMuestreoId","=","2"]
GET http://{{host}}:{{port}}/api/cadenascustodia?$filter=[%22eventoMuestreoId%22%2C%22%3D%22%2C%222%22]

### GET by Id
### ? 
GET http://{{host}}:{{port}}/api/cadenascustodia/1

### Updates
### ? Actualizar una cadena de custodia
PUT http://{{host}}:{{port}}/api/cadenascustodia/2
Content-Type: application/json

{
  "nombre": "Cadena Actual",
  "fecha": "2024-09-01",
  "laboratorioId": 1,
  "eventoMuestreoId": 2,
  "matrizCodigo": 2
}


### Create
### ? Crear una cadena de custodia
POST http://{{host}}:{{port}}/api/cadenascustodia/
Content-Type: application/json

{
  "nombre": "Cadena Delete",
  "fecha": "2024-09-02",
  "laboratorioId": 1,
  "eventoMuestreoId": 2,
  "matrizCodigo": 1
}

### Delete
### ? Borrar una cadena de custodia
DELETE http://{{host}}:{{port}}/api/cadenascustodia/3

