### proyectos/ 
#* allowedFields = ["id", "codigo", "nombre", "empresa"];

### GET 
### ? Todos los proyectos
GET http://localhost:5001/proyectos/

### ? Todos los Proyectos de empresa YPF
# Este request filtra proyectos cuya Empresa = 'YPF'
# Formato interno: ["empresa","=","YPF"]
GET http://localhost:5001/proyectos?$filter=[%22empresa%22%2C%22%3D%22%2C%22YPF%22]

### ? Proyectos entre 200111 y 200115 ambos inclusive
# Este request filtra proyectos con Codigo entre 200111 y 200115 (inclusive)
# Formato interno: [["codigo",">=","200111"],"and",["codigo","<=","200999"]]
GET http://localhost:5001/proyectos?$filter=%5B%5B%22codigo%22%2C%22%3E%3D%22%2C%22200111%22%5D%2C%22and%22%2C%5B%22codigo%22%2C%22%3C%3D%22%2C%22200999%22%5D%5D


### ? Los primeros 10 Proyectos YPF en orden ascendente de "nombre"
# y devuelve la primera página (10 ítems a partir del registro 0).
# Formato filtro interno: ["empresa","=","Vista"]
# Formato sort interno: [{"selector":"nombre","desc":false}]
GET http://localhost:5001/proyectos?$filter=[%22empresa%22,%22=%22,%22Vista%22]&$sort=[{%22selector%22:%22nombre%22,%22desc%22:false}]&$skip=0&$take=10

### ? Conjunto vacio por filtros combinados
# Este request prueba que deberia hacer con un Id de fila enfocada
# Formato interno: [["id","=","1"],"and",["codigo","contains","200115"]]
GET http://localhost:5001/proyectos?$filter=%5B%5B%22id%22%2C%22%3D%22%2C1%5D%2C%22and%22%2C%5B%22codigo%22%2C%22contains%22%2C%22200115%22%5D%5D

### Updates
### ? Actualizar un proyecto que no existe
PUT http://localhost:5001/proyectos/9
Content-Type: application/json

{
  "codigo": "200115",
  "nombre": "Proyecto 200115 actualizado 1",
  "empresa": "YPF"
}

### ? Actualizar un proyecto 
PUT http://localhost:5001/proyectos/1
Content-Type: application/json

{
  "sobra" : 17,
  "codigo": "200115",
  "nombre": "Proyecto 200115 actualizado 1",
  "empresa": "YPF"
}

### Create
### ? Crear un proyecto 
POST http://localhost:5001/proyectos/
Content-Type: application/json

{
  "codigo": "200335",
  "nombre": "Nuevo Proyecto 200335",
  "empresa": "YPF"
}

### Delete
### ? Borrar un proyecto
DELETE http://localhost:5001/proyectos/15

###
http://localhost:5001/proyectos?%24filter=%5B%22codigo%22%2C%22contains%22%2C%22200222%22%5D&%24sort=%5B%7B%22selector%22%3A%22nombre%22%2C%22desc%22%3Atrue%7D%2C%7B%22selector%22%3A%22id%22%2C%22desc%22%3Afalse%7D%5D&%24skip=0&%24take=10
