@host = localhost
@port = 5111
## mkcompuestos 
#* allowedFields = ["id", "subproyectoId", "compuestoId"];

### GET 
### ? Todos los compuestos en mkcompuestos
GET http://{{host}}:{{port}}/api/mkcompuestos/

### ? mkcompuestos por el subproyectoId
# Este request filtra compuestos con subproyectoId = '6'
# Formato interno: ["subproyectoId","=","6"]
GET http://{{host}}:{{port}}/api/mkcompuestos?$filter=[%22subproyectoId%22%2C%22%3D%22%2C%226%22]


### ? Get por ID
GET http://{{host}}:{{port}}/api/mkcompuestos/1

### Updates
### ? Actualizar un mkcompuestos que no existe
PUT http://{{host}}:{{port}}/api/mkcompuestos/45
Content-Type: application/json

{
  "subproyectoId": 6,
  "compuestoId":27,
  "umId":1
}

### ? Actualizar un mkcompuesto
PUT http://{{host}}:{{port}}/api/mkcompuestos/1
Content-Type: application/json

{
  "subproyectoId": 6,
  "compuestoId": 1,
  "umId":1

}


### Create
### ? Crear un mkcompuesto
POST http://{{host}}:{{port}}/api/mkcompuestos/
Content-Type: application/json

{
  "subproyectoId": 6,
  "compuestoId": 27,
  "umId":1
}


### Delete
### ? Borrar un mkcompuesto que no existe
DELETE http://{{host}}:{{port}}/api/mkcompuestos/10

### Delete
### ? Borrar un mkcompuesto que sí existe
DELETE http://{{host}}:{{port}}/api/mkcompuestos/7

### Reemplazar todos los compuestos de un subproyecto
POST http://{{host}}:{{port}}/api/mkcompuestos/replace
Content-Type: application/json

[
  {
    "subproyectoId": 29,
    "compuestoId": 1,
    "umId": 1
  },
  {
    "subproyectoId": 29,
    "compuestoId": 26,
     "umId": 1
  },
  {
    "subproyectoId": 29,
    "compuestoId": 27,
     "umId": 1
  },
  {
    "subproyectoId": 29,
    "compuestoId": 28,
     "umId": 1
  }
]