@host = localhost
@port = 5111
### POST
### ? Generar Excel Evolucion CDI
POST http://localhost:5001/evolucionCDI/
Content-Type: application/json

{
    "subproyectoId": 266,
    "proyectoNombre": "100000-100",
    "gruposConfig": [
        { "id": 1,
        "subproyectoId": 999, 
        "nombre": "Grupo1", 
        "pozos": [30, 31], 
        "graficos": [1, 3] 
        },
        { "id": 7, 
        "subproyectoId": 999, 
        "nombre": "Grupo2", 
        "pozos": [35], 
        "graficos": [1, 4] 
        }
    ],
    "graficosConfig": [
        { "id": 1, 
          "nombre": "NP-BTEX", 
          "eje1": [26, 27, 28, 129], 
          "eje2": [-1],
          "seccion": 2,
          "anexoNombre": "BTEX" 
        },
        { "id": 3, 
          "nombre": "Naftaleno", 
          "eje1": [90], 
          "eje2": [],
          "seccion": 2,
          "anexoNombre": "Naftaleno" 
        },
        { "id": 4, 
          "nombre": "PAHs-HTP", 
          "eje1": [90, 94], 
          "eje2": [1],
          "seccion": 1,
          "anexoNombre": "PAHs" 
        }
    ]
}
