### GET toma los datos para mandar a armar mannkendall - solo para pruebas porque el get std hace las 2 cosas
GET http://localhost:5001/mannKendall/data/55


### GET crea mannnKendall //TODO: cambiar a post
### ? 
GET http://localhost:5001/mannKendall/29?fecha=2025-04-12

### GET crea mannnKendall //TODO: cambiar a post
### ? sin fecha = today
GET http://localhost:5001/mannKendall/266

### POST
### ? Traer un zipfile con todos los xlsm
POST http://localhost:5001/mannkendall/getzip
Content-Type: application/json

{
  "archivos": [
  {
    "id": 0,
    "path": "C:/Netrona/Clientes/BfU/ProcesoProtocolos/MannKendall/Files/",
    "file": "MK_100000-100_HTP_2025-04-21.xlsm",
    "zipName": "MK_100000-100_2025-04-21"
  },
  {
    "id": 0,
    "path": "C:/Netrona/Clientes/BfU/ProcesoProtocolos/MannKendall/Files/",
    "file": "MK_100000-100_Benceno_2025-04-21.xlsm",
    "zipName": "MK_100000-100_2025-04-21"
  },
  {
    "id": 0,
    "path": "C:/Netrona/Clientes/BfU/ProcesoProtocolos/MannKendall/Files/",
    "file": "MK_100000-100_Tolueno_2025-04-21.xlsm",
    "zipName": "MK_100000-100_2025-04-21"
  }
]
}