INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Metil ter-Butil Eter (MTBE)', 'metilterbutiletermtbe', '34', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Tetraetilo de plomo', 'tetraetilodeplomo', '181', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico -  > nC10 - nC12', 'alifatico>nc10nc12', '13', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - > nC12 - nC16', 'alifatico>nc12nc16', '14', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - > nC16 - nC21', 'alifatico>nc16nc21', '15', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - > nC21 - nC35', 'alifatico>nc21nc35', '16', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - > nC6 - nC8', 'alifatico>nc6nc8', '11', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - > nC8 - nC10', 'alifatico>nc8nc10', '12', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - C6', 'alifaticoc6', '524', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC10 - nC12', 'aromatico>nc10nc12', '20', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC12 - nC16', 'aromatico>nc12nc16', '21', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC16 - nC21', 'aromatico>nc16nc21', '22', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC21 - nC35', 'aromatico>nc21nc35', '23', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC7 - nC8', 'aromatico>nc7nc8', '18', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC8 - nC10', 'aromatico>nc8nc10', '19', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('TPH Total 1006', 'tphtotal1006', '1', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('MRO C28-C35*', 'mroc28c35', '4', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Hidrocarburos aromáticos polinucleares (PAHs)*', 'hidrocarburosaromaticospolinuclearespahs', '89', '1');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Xilenos (Totales)', 'xilenostotales', '330', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Plomo Total (Pb)*', 'plomototalpb', '450', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Metil ter-Butil Eter (MTBE)', 'metilterbutiletermtbe', '335', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Hidrocarburos aromáticos polinucleares (PAHs)', 'hidrocarburosaromaticospolinuclearespahs', '390', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - C6*', 'alifaticoc6', '526', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - > nC6 - nC8', 'alifatico>nc6nc8', '312', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - > nC8 - nC10', 'alifatico>nc8nc10', '313', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico -  > nC10 - nC12', 'alifatico>nc10nc12', '314', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - > nC12 - nC16', 'alifatico>nc12nc16', '315', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - > nC16 - nC21', 'alifatico>nc16nc21', '316', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Alifatico - > nC21 - nC35', 'alifatico>nc21nc35', '317', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC7 - nC8', 'aromatico>nc7nc8', '319', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC8 - nC10', 'aromatico>nc8nc10', '320', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC10 - nC12', 'aromatico>nc10nc12', '321', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC12 - nC16', 'aromatico>nc12nc16', '322', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC16 - nC21', 'aromatico>nc16nc21', '323', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Aromatico - > nC21 - nC35', 'aromatico>nc21nc35', '324', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('TPH Total 1006', 'tphtotal1006', '301', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Hidrocarburos Aromáticos Polinucleares (PAH)', 'hidrocarburosaromaticospolinuclearespah', '390', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('COT (Carbono Orgánico Total)', 'cotcarbonoorganicototal', '441', '3');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('m,p-Xilenos', 'mpxilenos', '207', '2');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Xilenos (Totales)', 'xilenostotales', '206', '2');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('Hidrocarburos Totales.', 'hidrocarburostotales', '209', '2');
INSERT INTO SinonimosCompuestos (TextoLab, TextoProcesado, CompuestoId,MatrizId) VALUES ('TPH Total 1006*', 'tphtotal1006', '209', '2');
